import {
  AlertTriangle,
  ArrowRight,
  Book,
  Check,
  ChevronLeft,
  ChevronRight,
  Command,
  CreditCard,
  File,
  FileText,
  Github as GitHubIcon,
  HelpCircle,
  Image,
  Laptop,
  Loader2,
  Mail as MailIcon,
  Moon,
  MoreVertical,
  Pizza,
  Plus,
  Settings,
  SunMedium,
  Ticket,
  Trash,
  Twitter as TwitterIcon,
  User,
  X,
  type LucideIcon,
} from "lucide-react"

export type Icon = LucideIcon;

export const Icons = {
  logo: Command,
  close: X,
  spinner: Loader2,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  trash: Trash,
  post: FileText,
  page: File,
  media: Image,
  settings: Settings,
  billing: CreditCard,
  ellipsis: MoreVertical,
  add: Plus,
  warning: AlertTriangle,
  user: User,
  arrowRight: ArrowRight,
  help: HelpCircle,
  pizza: Pizza,
  sun: SunMedium,
  moon: Moon,
  laptop: Laptop,
  gitHub: GitHubIcon,
  google: MailIcon,
  check: Check,
  twitter: TwitterIcon,
  book: Book,
  ticket: Ticket,
} as const 